RHVoice/packages

src/languages/pl/impl.json, src/languages/pl/language.json, src/languages/pl/voices/magda.json, src/languages/pl/voices/natan.json
This will make sure that RHvoice uses the new format
=> adding latest polish to beta

src/languages/pl/impl.json, src/languages/pl/language.json, src/languages/pl/voices/magda.json, src/languages/pl/voices/natan.json
Here is the 8th revisio. It needs to be the part of apks.
=> 8th revision of the language

src/languages/pl/voices/natan.json
Intended for merging ti alpha, if works in dev. This will be identical to final, if all works well.
=> Natan voice update

src/languages/pl/voices/natan.json
The fix was tested and all works. 
This is ready for merging to alpha. 
That means, If i declare natan 4.8 ready for testing.
=> fix: sample of the natan voice

src/languages/pl/impl.json, src/languages/pl/voices/magda.json, src/languages/pl/voices/natan.json
This update fixes voice quality and pronounciation errors.
=> Polish language and Magda update

src/languages/pl/impl.json, src/languages/pl/voices/natan.json, src/languages/uk/voices/anatol.json
This pull request adds updated Anatol, polish language, as well as updated Natan voice.
Users tested these changes locally in the dev version, and these don't make the troubles during upgrade. All wentt smoothly, so it's intended for stable.
=> Anatol voice bugfix update, version to 4.2, Natan polish voice and polish language for android

src/languages/uk/voices/volodymyr.json
=> Update Volodymyr to 4.1

src/languages/uk/voices/natalia.json
World compatible. It is ready for two flawors of the app: stable and alpha. Tested this on the dev app.
=> Natalia voice update, 

src/languages/ru/voices/elena.json
Elena now uses world. updated to v 4.3
=> Updated elena to v 4.3

src/languages/pl/voices/natan.json
Yet another version which fixes voice quality, and it is tested internally by users, using my unofficial dev directory.
This is ready for three flavours: stable, dev and alpha.
=> Natav v4.10

src/languages/pl/voices/michal.json
This voice received the positive feedback among polish users, so after the long time, i am publishing it.
This should propagate to our all three branches, as it is thoroughly tested.
=> Michal voice - polish

src/languages/ru/voices/timofey.json
All local checks passed. This is the new russian voice.
=> Timofey - russian

src/languages/en/voices/lyubov.json
Updated Lyubov to v 4.1, using world vocoder, fixed the pronounciation bugs of the voice.
=> Lyubov voice - english - update

src/languages/en/voices/slt.json
Updated Slt to v 4.1, fixed pronounciation issues, and unintentional wovel lenghthening.
=> Slt - english- v4.1 update

src/languages/pl/voices/alicja.json
Yet another polish voice made with world.
=> New voice - Alicja

src/languages/pl/impl.json
New update containing more fixes to the dictionary
=> Polish language update to version 12

src/languages/en/impl.json, src/languages/ka/impl.json, src/languages/ky/impl.json, src/languages/mk/impl.json, src/languages/pl/impl.json, src/languages/pt/impl.json, src/languages/ru/impl.json, src/languages/sq/impl.json, src/languages/uk/impl.json
All checked with python3 check script. Checksum passes.
=> Updated languages for 0.10.0

src/languages/pl/voices/natan.json
This update is thoroughly tested for the alpha and stable 1.10 branches respectively. It is ready tto land there.
=> Natan 4.11 update

src/languages/eo/voices/spomenka.json
updated the spomenka voice. Soon i am going to update the packages.
=> Spomenka - epo - voice update

src/languages/uk/voices/natalia.json
Corrected the voice quality. This was tested in dev extensively, and it is ready for alpha and stable.
=> Updated Natalia voice to new version

src/languages/uk/voices/marianna.json
Updated the voice: it takes all advantages of world.
Ready for merging to all branches
=> Mariana ukr - v 4.1 update

src/languages/pl/voices/cezary.json
=> New polish voice - Cezary v 4.0

src/languages/ru/voices/vsevolod.json
=> new voice: vsevolod-rus

src/languages/uk/impl.json
New dictionary, apostrophe handling fix. Because of the apostrophe handling fix, it needed update for the new core.
=> Ukrainian update

src/languages/pl/voices/cezary.json, src/languages/pl/voices/michal.json, src/languages/pl/voices/natan.json
Intended for new cores, because of the voicing parameter. It just gives benefit to these voices.
=> Cezary, michal and natan for 1.12.0 core

src/languages/eo/voices/spomenka.json
This version drastically improves the quality, and corrects the unvoiced parts of the every spoken utterance.
=> spomenka - epo voice v 4.2

src/languages/uk/impl.json
=> Ukrainian update to v 1.21updated ukrainian to 1.21, fix to the dictionary update

src/languages/cs/impl.json, src/languages/cs/language.json, src/languages/cs/voices/zdenek.json
I will request my Czech beta testers to join the alpha branch.
=> Czech language and voice on android

src/languages/cs/impl.json, src/languages/cs/language.json, src/languages/cs/voices/zdenek.json
=> fix for the locale in json

README.md, src/languages/sk/impl.json, src/languages/sk/language.json, src/languages/sk/voices/ondro.json
Coauthored with @pvagner
Intended for dev and beta for now.
=> Slovak language and voice for androidOndro - first slovak male voice

src/languages/cs/impl.json, src/languages/cs/voices/zdenek.json, src/languages/sk/impl.json, src/languages/sk/voices/ondro.json
New voice data, and language corrections collected by users. Intended for stable.
=> Slovak and czech updates

src/languages/uk/impl.json
=> Ukrainian updated to 1.24

src/languages/cs/impl.json, src/languages/eo/impl.json, src/languages/ka/impl.json, src/languages/ky/impl.json, src/languages/mk/impl.json, src/languages/pl/impl.json, src/languages/pt/impl.json, src/languages/ru/impl.json, src/languages/sk/impl.json, src/languages/sk/voices/ondro.json, src/languages/sq/impl.json, src/languages/tt/impl.json, src/languages/uk/impl.json, src/languages/uz/impl.json
Updated languages with the latest improvements.
Updated slovak Ondro voice.
=> Language updates for android

README.md, src/languages/sr/impl.json, src/languages/sr/language.json, src/languages/sr/voices/dragana.json
Added dragana voice,
Added serbian language,
Readme: added the test message for the voice.
=> Serbian: new language and voice in android version

src/languages/sr/impl.json, src/languages/sr/voices/dragana.json
Ready for publishing to stable
=> android: new Dragana voice and serbian language

src/languages/uk/impl.json
This bumps ukrainian to 1.26 with accentuation fixes.
=> Ukrainian for android

src/languages/en/voices/ksp.json
* ready for the stable production. This pased all internal checks.
=> Indian english: update on android

README.md, src/languages/hr/impl.json, src/languages/hr/language.json, src/languages/hr/voices/karmela.json
* croatian language,
* first female voice,
* sample text for croatian
=> Croatian language

src/languages/hr/impl.json, src/languages/sr/impl.json
=> Serbian and croatian: fxed the problem of slow loading on android and possible other platforms

src/languages/ru/voices/seva.json
=> Seva - rus

src/languages/cs/impl.json, src/languages/cs/voices/radek.json, src/languages/cs/voices/zdenek.json, src/languages/pl/impl.json, src/languages/sk/impl.json
This language update updates: czesh, slovak and polish emoji data, as well as adds fixes to pronounciation and rules.
=> Language data update - dictionaries and rules refinements
